//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts
{
    
    
    /// <summary>
    /// The ActivityContractSection Configuration Section.
    /// </summary>
    public partial class ActivityContractSection : global::System.Configuration.ConfigurationSection
    {
        /// <summary>
        /// The XML name of the ActivityContractSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ActivityContractSectionSectionName = "activityContractSection";
        
        /// <summary>
        /// Gets the ActivityContractSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public static global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractSection Instance
        {
            get
            {
                return ((global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractSection)(global::System.Configuration.ConfigurationManager.GetSection(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractSection.ActivityContractSectionSectionName)));
            }
        }

        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractSection.XmlnsPropertyName]));
            }
        }

        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }

        /// <summary>
        /// The XML name of the <see cref="ActivityContracts"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ActivityContractsPropertyName = "activityContracts";
        
        /// <summary>
        /// Gets or sets the ActivityContracts.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ActivityContracts.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractSection.ActivityContractsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElementCollection ActivityContracts
        {
            get
            {
                return ((global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElementCollection)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractSection.ActivityContractsPropertyName]));
            }
            set
            {
                base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractSection.ActivityContractsPropertyName] = value;
            }
        }
    }
}
namespace Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts
{
    
    
    /// <summary>
    /// The ActivityContractElement Configuration Element.
    /// </summary>
    public partial class ActivityContractElement : global::System.Configuration.ConfigurationElement
    {
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }

        /// <summary>
        /// The XML name of the <see cref="Id"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string IdPropertyName = "id";
        
        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Id.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.IdPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Id
        {
            get
            {
                return ((string)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.IdPropertyName]));
            }
            set
            {
                base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.IdPropertyName] = value;
            }
        }

        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.NamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.NamePropertyName]));
            }
            set
            {
                base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.NamePropertyName] = value;
            }
        }

        /// <summary>
        /// The XML name of the <see cref="Code"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string CodePropertyName = "code";
        
        /// <summary>
        /// Gets or sets the Code.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Code.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.CodePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Code
        {
            get
            {
                return ((string)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.CodePropertyName]));
            }
            set
            {
                base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.CodePropertyName] = value;
            }
        }

        /// <summary>
        /// The XML name of the <see cref="Description"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DescriptionPropertyName = "description";
        
        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Description.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.DescriptionPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Description
        {
            get
            {
                return ((string)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.DescriptionPropertyName]));
            }
            set
            {
                base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.DescriptionPropertyName] = value;
            }
        }

        /// <summary>
        /// The XML name of the <see cref="OperatorName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string OperatorNamePropertyName = "operatorName";
        
        /// <summary>
        /// Gets or sets the OperatorName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The OperatorName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.OperatorNamePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string OperatorName
        {
            get
            {
                return ((string)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.OperatorNamePropertyName]));
            }
            set
            {
                base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.OperatorNamePropertyName] = value;
            }
        }

        /// <summary>
        /// The XML name of the <see cref="OperatorMethod"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string OperatorMethodPropertyName = "operatorMethod";
        
        /// <summary>
        /// Gets or sets the OperatorMethod.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The OperatorMethod.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.OperatorMethodPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string OperatorMethod
        {
            get
            {
                return ((string)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.OperatorMethodPropertyName]));
            }
            set
            {
                base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.OperatorMethodPropertyName] = value;
            }
        }

        /// <summary>
        /// The XML name of the <see cref="ActivityContract"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ActivityContractPropertyName = "activityContract";
        
        /// <summary>
        /// Gets or sets the ActivityContract.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ActivityContract.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.ActivityContractPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string ActivityContract
        {
            get
            {
                return ((string)(base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.ActivityContractPropertyName]));
            }
            set
            {
                base[global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement.ActivityContractPropertyName] = value;
            }
        }
    }
}
namespace Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts
{
    
    
    /// <summary>
    /// A collection of ActivityContractElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElementCollection.ActivityContractElementPropertyName)]
    public partial class ActivityContractElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        /// <summary>
        /// The XML name of the individual <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ActivityContractElementPropertyName = "activityContractElement";

        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElementCollection.ActivityContractElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElementCollection.ActivityContractElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement)(element)).Id;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement();
        }

        /// <summary>
        /// Gets the <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement this[int index]
        {
            get
            {
                return ((global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> with the specified key.
        /// </summary>
        /// <param name="id">The key of the <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement this[object id]
        {
            get
            {
                return ((global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement)(base.BaseGet(id)));
            }
        }

        /// <summary>
        /// Adds the specified <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="activityContractElement">The <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement activityContractElement)
        {
            base.BaseAdd(activityContractElement);
        }

        /// <summary>
        /// Removes the specified <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="activityContractElement">The <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement activityContractElement)
        {
            base.BaseRemove(this.GetElementKey(activityContractElement));
        }

        /// <summary>
        /// Gets the <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement GetItemAt(int index)
        {
            return ((global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> with the specified key.
        /// </summary>
        /// <param name="id">The key of the <see cref="global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement GetItemByKey(string id)
        {
            return ((global::Kengic.Was.CrossCutting.ConfigurationSection.ActivityContracts.ActivityContractElement)(base.BaseGet(((object)(id)))));
        }

        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
    }
}
